version: '3.3'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: netflix-db
        restart: always
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=myNetflixDb@2018
            - MSSQL_PID=Express
        ports:
            - "1433:1433" 
        volumes:
            - db_data:/var/lib/data 
    zkpr:
        image: wurstmeister/zookeeper
        container_name: netflix-zkpr
        hostname: netflix-zkpr
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        restart: always
        ports:
            - "2181:2181"
    kfk:
        image: wurstmeister/kafka
        command: [start-kafka.sh]
        container_name: netflix-kfk
        hostname: netflix-kfk
        environment:
            KAFKA_ADVERTISED_HOST_NAME: netflix-kfk # docker-machine ip
            KAFKA_ZOOKEEPER_CONNECT: netflix-zkpr:2181
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://netflix-kfk:9092 # when running all in containers
        ports:
            - "9092:9092"
        depends_on:
            - "zkpr"
    cache:
        image: redis
        container_name: netflix-redis
        restart: always
        ports:
            - "6379:6379"
        expose:
            - 6379
volumes:
    db_data:
