version: '3.3'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: netflix-db
        restart: always
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=myNetflixDb@2018
            - MSSQL_PID=Express
        ports:
            - "1433:1433" 
        volumes:
            - db_data:/var/lib/data 
    zkpr:
        image: zookeeper
        container_name: netflix-zkpr
        restart: always
        ports:
            - "2181:2181"
    kfk:
        image: ches/kafka
        container_name: netflix-kfk
        environment:
            - ZOOKEEPER_IP=netflix-zkpr
    cache:
        image: redis
        container_name: netflix-redis
        restart: always
        ports:
            - "6379:6379"
        expose:
            - 6379
volumes:
    db_data:
