version: '3.3'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: netflix-db
        restart: always
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=myNetflixDb@2018
            - MSSQL_PID=Express
        ports:
            - "1433:1433" 
        volumes:
            - db_data:/var/lib/data 
volumes:
    db_data:
